#!/bin/bash

VERSION=v0.1.1

HOST=127.0.0.1
PORT=8500
ALERT_STATUS=2

while getopts h:p:vcw OPT; do
    case $OPT in
        h)
            HOST=$OPTARG;;
        p)
            PORT=$OPTARG;;
        c)
            ALERT_STATUS=2;;
        w)
            ALERT_STATUS=1;;
        v)
            echo $VERSION;
            exit 0;;
    esac
done

curl -s http://$HOST:$PORT/v1/status/leader | fgrep -q '""'

STATUS=$?

if [[ $STATUS == "0" ]]; then
    exit $ALERT_STATUS
elif [[ $STATUS == "1" ]]; then
    exit 0
fi
