#!/bin/bash

VERSION=v0.1.1

HOST=127.0.0.1
PORT=8500
TEMP_FILE=/var/tmp/mackerel-agent/consul-server-nodes-changed
ALERT_STATUS=2

while getopts h:p:t:vcw OPT; do
    case $OPT in
        h)
            HOST=$OPTARG;;
        p)
            PORT=$OPTARG;;
        t)
            TEMP_FILE=$OPTARG;;
        c)
            ALERT_STATUS=2;;
        w)
            ALERT_STATUS=1;;
        v)
            echo $VERSION;
            exit 0;;
    esac
done

PEERS="$(curl -s http://$HOST:$PORT/v1/status/peers)"

if [[ ! -f $TEMP_FILE ]]; then
    echo "$PEERS" > $TEMP_FILE
fi

diff $TEMP_FILE <(echo "$PEERS")

STATUS=$?

echo "$PEERS" > $TEMP_FILE

if [[ $STATUS != "0" ]]; then
    exit $ALERT_STATUS
fi

exit 0
