#!/bin/bash

VERSION=v0.1.1

HOST=127.0.0.1
PORT=8500
TEMP_FILE=/var/tmp/mackerel-agent/consul-server-nodes-changed

while getopts h:p:t:v OPT; do
    case $OPT in
        h)
            HOST=$OPTARG;;
        p)
            PORT=$OPTARG;;
        t)
            TEMP_FILE=$OPTARG;;
        v)
            echo $VERSION;
            exit 0;;
    esac
done

PREV_PEERS="$([[ -f $TEMP_FILE ]] && cat $TEMP_FILE)"
PEERS="$(curl -s http://$HOST:$PORT/v1/status/peers | tee $TEMP_FILE)"

if [[ $PREV_PEERS != $PEERS ]]; then
    exit 1
fi
